server:
  port: 8080 # ???????

spring:
  application:
    name: pet-dispatch-pro
  # 👇 新加这两行：告诉系统，本地运行时去合并 application-local.yml 的配置
  profiles:
    active: local

  # ???????? (????)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ????? url ????????????? pet_dispatch_pro ?????????????
    url: jdbc:mysql://localhost:3306/pet_dispatch_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: '0206'

  # Redis ???? (???? LBS ??????????)
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456

# MyBatis-Plus ???? (?????)
mybatis-plus:
  configuration:
    # ??????????????? (????? create_time ?????? Java ? createTime)
    map-underscore-to-camel-case: true
    # Debug ???????????? SQL ????????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # ??????????? (???????? AUTO_INCREMENT)
      id-type: auto

wenxu:
  alioss:
    # 使用占位符，动态读取隐藏环境中的值。冒号后面是防止报错的默认提示语。
    endpoint: ${wenxu.alioss.endpoint:}
    access-key-id: ${wenxu.alioss.access-key-id:}
    access-key-secret: ${wenxu.alioss.access-key-secret:}
    bucket-name: ${wenxu.alioss.bucket-name:}
